name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/* --skip-existing --disable-progress-bar
    - name: Publish AUR
      env:
        AUR_KEY: ${{ secrets.AUR_KEY }}
      run: |
        mkdir ~/.ssh
        echo -e $AUR_KEY > ~/.ssh/aur
        echo -e 'Host aur.archlinux.org\n\tIdentityFile ~/.ssh/aur\n\tUser aur' > ~/.ssh/config
        chmod 600 ~/.ssh/aur
        _VERSION=$(cat VERSION)
        git submodule init
        git submodule update
        cd aur
        git pull
        sed -i -E "s/^pkgver=.+\$/pkgver=${_VERSION}/" PKGBUILD
        docker run --rm -t -v "$(pwd):/aur" archlinux 'makepkg --printsrcinfo > /aur/.SRCINFO'
        git add .SRCINFO PKGBUILD
        git commit -m "Update to ${_VERSION}"
        git push --force
