name: Synthetic Test

on:
  schedule:
    - cron: 15 3 * * *
  workflow_dispatch:


jobs:
  synthetic_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip flit
          flit install --only-deps
      - name: Test
        env:
          ENABLE_SYNTHETIC: 1
          TCAFE_ID: '${{ secrets.TCAFE_ID }}'
          TCAFE_PWD: '${{ secrets.TCAFE_PWD }}'
        run: pytest test/test_api.py::test_synthetic
